In [1]:
import tensorflow as tf
import tensorflow.keras as tfk
import tensorflow.keras.layers as tfkl
from tensorflow.keras.models import Sequential


from google.colab import drive
import numpy as np
import pandas as pd

In this example, we're going to train a [CharRNN](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) on a body of Shakespearian text. Ultimtely, this is an unsuperived learning task. But similar to our previous explorations in unsupervised DL, we will use an unlabeled dataset and create many samples of labeled data that we can use with our familiar supervised loss functions. The result will be a model that has learned the statistical properties of the input text, and can then be considered a "generative" model of language because we can use it to generate synthetic passages of Shakespeare.  

In [2]:
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [4]:
file_path = "shakespeare.txt"

with open(file_path,"r") as f:
  text = f.read()

We've loaded our Shakespeare text, let's take a look at a random snippet.

In [5]:
print(text[31600:32000])

 lies i' the second chamber?
  LADY MACBETH. Donalbain.
  MACBETH. This is a sorry sight.           [Looks on his hands.
  LADY MACBETH. A foolish thought, to say a sorry sight.
  MACBETH. There's one did laugh in 's sleep, and one cried,
      "Murther!"
    That they did wake each other. I stood and heard them,
    But they did say their prayers and address'd them
    Again to sleep.
  LADY MACB


We need to convert our text into numeric arrays, the next several blocks accomplish this.

First, we'll create a mapping between characters and their numeric index. We'll also create the reverse mapping, which is useful.

In [6]:
chars = sorted(list(set(text)))
print('total chars:', len(chars))
char_indices = dict((c, i) for i, c in enumerate(chars))
indices_char = dict((i, c) for i, c in enumerate(chars))

total chars: 75


Next, we'll create a training set of sub-sequences. Remember, we're trying to train a model to be able to predict the next chracter if it is given several characters of a subsequence. So we will create training pairs where each X is a fixed-length subsequences and each Y is the corresponding next letter in the text.

In [7]:
maxlen = 40
step = 3
sub_sequences = []
next_chars = []
for i in range(0, len(text) - maxlen, step):
    sub_sequences.append(text[i: i + maxlen])
    next_chars.append(text[i + maxlen])
print('nb sequences:', len(sub_sequences))

nb sequences: 38700


In [8]:
k=300
print("(Sequence):\n" + sub_sequences[k])
print("\n(Target Character): \n" + next_chars[k])

(Sequence):
 and other Apparitions
  Lords, Gentleme

(Target Character): 
n


Next we'll create one-hot vectors for our sub-sequences. The tensor we create here will be shaped as (num_sequences x sequence_length x alphabet_size).

In [9]:
X = np.zeros((len(sub_sequences), maxlen, len(chars)), dtype=np.uint8 )
Y = np.zeros((len(sub_sequences), len(chars)), dtype=np.uint8)
for i, seq in enumerate(sub_sequences):
    for t, char in enumerate(seq):
        X[i, t, char_indices[char]] = 1
        Y[i, char_indices[next_chars[i]]] = 1

In [10]:
X[0,0,:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=uint8)

In [11]:
Y[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

Our RNN model will be quite simple.

In [12]:
char_rnn = Sequential()
char_rnn.add(tfkl.LSTM(128, input_shape=(maxlen, len(chars)))) 
char_rnn.add(tfkl.Dense(len(chars),activation="softmax"))

In [14]:
char_rnn.compile(loss='categorical_crossentropy', optimizer=tfk.optimizers.RMSprop(lr=0.01))

In [15]:
char_rnn.fit(X,Y, epochs=20, batch_size=1024)

Epoch 1/20
38/38 [==============================] - 1s 18ms/step - loss: 3.3015
Epoch 2/20
38/38 [==============================] - 1s 15ms/step - loss: 2.9389
Epoch 3/20
38/38 [==============================] - 1s 15ms/step - loss: 2.5962
Epoch 4/20
38/38 [==============================] - 1s 15ms/step - loss: 2.3783
Epoch 5/20
38/38 [==============================] - 1s 15ms/step - loss: 2.1320
Epoch 6/20
38/38 [==============================] - 1s 15ms/step - loss: 1.9674
Epoch 7/20
38/38 [==============================] - 1s 15ms/step - loss: 1.8451
Epoch 8/20
38/38 [==============================] - 1s 15ms/step - loss: 1.7489
Epoch 9/20
38/38 [==============================] - 1s 15ms/step - loss: 1.6790
Epoch 10/20
38/38 [==============================] - 1s 15ms/step - loss: 1.6122
Epoch 11/20
38/38 [==============================] - 1s 15ms/step - loss: 1.5551
Epoch 12/20
38/38 [==============================] - 1s 15ms/step - loss: 1.5080
Epoch 13/20
38/38 [==================

Once we have a trained model, we can simulate new text by making predictions about the next character and then drawing characters in proportion to the predicted probabilities. And then simple repeat that process over and over, each time drawing the next character.

In [16]:
def draw_char(probs):
    probs = np.asarray(probs).astype('float64')
    if sum(probs) != 1.0:
      probs = probs / np.sum(probs)
    draw = np.random.choice(range(len(probs)) , p=probs)
    return draw

def sample_text(model, sample_length=100):
    start = np.random.randint(0, len(text) - maxlen - 1)
    sequence = text[start: start + maxlen]
  
    x_preds = np.zeros((sample_length, maxlen, len(chars)))
    for i in range(sample_length):
        for t, char in enumerate(sequence[-maxlen:]):
            x_preds[i, t, char_indices[char]] = 1.

        preds = model.predict(np.expand_dims(x_preds[i,:,:], axis=0), verbose=0)[0]
        next_index = draw_char(preds)
        next_char = indices_char[next_index]

        sequence += next_char
    return sequence

In [17]:
sim = sample_text(char_rnn,sample_length=500) 

In [18]:
print(sim)

Shakes so my single state of man that fuly.
    To searust villorren.
  SIWARD. Thangs. Kny lavef; of Attust?
Year, eiverance. Banquo,
    With show my dand and mine is Sins. Conith,

  MALCOLM. Melbenty thexerter's.
Come, men wife blastaing faighen deep
    Whose duccharess hath rewond on of thing fell?
    And theum lime, withet. Weat mare thus onure
    In chicking like pamacun. 
  LENNOX. They! Lean Axpersen! Lad that ither?

             Exeunt. Aly injuet
    be sould painting have the word youn deywon
    Thoush plessed in what


Notice that we can do pretty well to learn the typical statistical patterns of this text and then simulate new text that appears to be very similar to legitimate Shakespeare. 

But just a caution - we can also do pretty well with a much simpler method (Markov model): http://nbviewer.jupyter.org/gist/yoavg/d76121dfde2618422139

So the lesson is to try something simple before jumping right in to deep learning.

## Exercise

In this example, we're going to use an RNN for sequence classification. The task we'll set up is to generate a training set of randomized strings, and train our model to detect whether a string contains any vowels.

First, we'll create a training dataset of short randomized character sequences and the corresponding label of whether or not they contain at least one vowel.

In [19]:
import string

In [20]:
def contains_vowels(sequence):
  vowels = ["a", "e", "i", "o", "u"]
  return any([vowel in list(sequence) for vowel in vowels])

In [21]:
contains_vowels("gradient")

True

In [22]:
sequences = []
labels = []
for i in range(1000):
 char_list = np.random.choice( list(string.ascii_lowercase), size = 5, replace=True)
 seq = "".join(char_list)
 sequences.append(seq)
 labels.append(int(contains_vowels(seq)))

In [23]:
df = pd.DataFrame({"sequence": sequences, "label":labels})

In [24]:
df.head()

sequence  label
0    oeqya      1
1    zmfgc      0
2    sibij      1
3    chozr      1
4    ywsno      1

Next, set up and train an RNN (of any type) to solve this task. What preprocessing will you need to do first on the raw data in order to prepare it for the network?

In [45]:
# Data Preprocessing
# your code here
# print(sorted(list(set(df['sequence']))))
all_char=''
for i in range(len(df['sequence'])):
  all_char+=df['sequence'][i] # append all the character into a string 
#all_char
# find all characters 
chars=(sorted(list(set(all_char)))) # find unique characters and sort them 
print('total chars:', len(chars))
char_indices = dict((c, i) for i, c in enumerate(chars))
print(char_indices)
indices_char = dict((i, c) for i, c in enumerate(chars))
print(indices_char)

total chars: 26
{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}
{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j', 10: 'k', 11: 'l', 12: 'm', 13: 'n', 14: 'o', 15: 'p', 16: 'q', 17: 'r', 18: 's', 19: 't', 20: 'u', 21: 'v', 22: 'w', 23: 'x', 24: 'y', 25: 'z'}


In [52]:
maxlen=5
X = np.zeros((len(sequences), maxlen, len(chars)), dtype=np.uint8 )
for i, seq in enumerate(sequences):
  for t,char in enumerate(seq):
        X[i,t,char_indices[char]] = 1

Y = np.array(labels)

In [53]:
print(X)
print(Y)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 1 0]
  [1 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 1]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 1 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 1 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 1 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [1 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
[1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 1 1 0
 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0
 0 0 1 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1
 0 0 0 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 1 1 0 1
 1 0 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 0
 1 1 1 

In [60]:
model = Sequential()
model.add(tfkl.LSTM(64, input_shape=(5,26)))
model.add(tfkl.Dense(1,activation="sigmoid"))
model.compile(loss='binary_crossentropy', optimizer=tfk.optimizers.RMSprop(lr=0.01),metrics=['accuracy'])
model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 64)                23296     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 23,361
Trainable params: 23,361
Non-trainable params: 0
_________________________________________________________________


In [61]:
results = model.fit(X,Y,epochs=20,steps_per_epoch=5,batch_size=200)

Epoch 1/20
5/5 [==============================] - 0s 4ms/step - loss: 0.6580 - accuracy: 0.6540
Epoch 2/20
5/5 [==============================] - 0s 3ms/step - loss: 0.3968 - accuracy: 0.8400
Epoch 3/20
5/5 [==============================] - 0s 3ms/step - loss: 0.2442 - accuracy: 0.9420
Epoch 4/20
5/5 [==============================] - 0s 3ms/step - loss: 0.2374 - accuracy: 0.9090
Epoch 5/20
5/5 [==============================] - 0s 3ms/step - loss: 0.1507 - accuracy: 0.9690
Epoch 6/20
5/5 [==============================] - 0s 3ms/step - loss: 0.2138 - accuracy: 0.9180
Epoch 7/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0879 - accuracy: 0.9890
Epoch 8/20
5/5 [==============================] - 0s 3ms/step - loss: 0.1748 - accuracy: 0.9620
Epoch 9/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0728 - accuracy: 1.0000
Epoch 10/20
5/5 [==============================] - 0s 3ms/step - loss: 0.0380 - accuracy: 1.0000
Epoch 11/20
5/5 [======================

In [ ]:
# The accuracy was 1.000 after 20 epoch 
# The loss reduced to 0.0014 after 20 epoch